### Variables 
@port = 3000

### Get menu

GET http://localhost:{{port}}/api/menu

### Post menu item 
POST http://localhost:{{port}}/api/menu 
Content-Type: application/json

{

    "name": "Diavolo", 
    "price": "$20.00", 
    "description": "San Marzano tomato sauce, cayenne pepper, hot calabrese salami, onion, red bell pepper, and mozzarella.", 
    "image": "img/pizza2sm.jpg"

}

### Update menu item 
PUT http://localhost:{{port}}/api/menu/663ac51757f32188028b5351 
Content-Type: application/json

{

    "name": "Bruschetta", 
    "price": "$11.50", 
    "description": "Wood fired home made Italian bread, served with extra virgin olive oil", 
    "image": "img/app1sm.jpg"

}

### Delete menu item 
DELETE http://localhost:{{port}}/api/menu/663d59f878bbe63d0743bb58

### Get events 
GET http://localhost:{{port}}/api/events

### Get events by id 
GET http://localhost:{{port}}/api/events/663d628091f804f69a988590

### Post event item 
POST http://localhost:{{port}}/api/events 
Content-Type: application/json

{ 
  "name": "Oshkosh Farmers Market", 
  "location": "Oshkosh Town Square", 
  "date": "August 11, 2024", 
  "hours": "9 AM to 2:30 PM"
}

### Update event 
PUT http://localhost:{{port}}/api/events/663d628091f804f69a988590 
Content-Type: application/json

{

  "name": "Milwaukee Food Festival", 
  "location": "Milwaukee Public Market", 
  "date": "June 19, 2024", 
  "hours": "11 AM to 7 PM"

}

### Delete event 
DELETE http://localhost:{{port}}/api/events/663e78fff3fa176552e90703

